run:
  deadline: 10m
  issues-exit-code: 50
  modules-download-mode: readonly
linters:
  disable-all: false
  enable-all: false
  enable:
    - megacheck
    - staticcheck
    - deadcode
    - varcheck
    - gosimple
    - unused
    - prealloc
    - scopelint
    - gocritic
    - goimports
    - unconvert
    - govet
    - nakedret
    - structcheck
    - gosec
    - errcheck
    - ineffassign


  disable:
    - maligned
    - interfacer
    - typecheck
    - dupl
